set echo on;
spool mau_schema_output.txt;
-- Student id: 30504457
-- Student Name: Tan Wen Zheng

-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-12 20:57:33 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibit CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

DROP TABLE status CASCADE CONSTRAINTS;

DROP TABLE style CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code     NUMBER(4) NOT NULL,
    artist_fname    VARCHAR2(30) NOT NULL,
    artist_lname    VARCHAR2(50) NOT NULL,
    artist_street   VARCHAR2(20) NOT NULL,
    artist_town     VARCHAR2(10) NOT NULL,
    artist_state    CHAR(3) NOT NULL,
    artist_tel_no   CHAR(10)
);

COMMENT ON COLUMN artist.artist_code IS
    'Artist identifier';

COMMENT ON COLUMN artist.artist_fname IS
    'Artist first name';

COMMENT ON COLUMN artist.artist_lname IS
    'Artist last name';

COMMENT ON COLUMN artist.artist_street IS
    'Artist street address';

COMMENT ON COLUMN artist.artist_town IS
    'Artist town address';

COMMENT ON COLUMN artist.artist_state IS
    'Artist state address';

COMMENT ON COLUMN artist.artist_tel_no IS
    'Artist phone number';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artwork_no            NUMBER(2) NOT NULL,
    artist_code           NUMBER(4) NOT NULL,
    artwork_title         VARCHAR2(50) NOT NULL,
    artwork_date          DATE NOT NULL,
    media_name            VARCHAR2(24) NOT NULL,
    min_price             NUMBER(8) NOT NULL,
    date_added_to_stock   DATE,
    artwork_style_no      NUMBER(2) NOT NULL
);

COMMENT ON COLUMN artwork.artwork_no IS
    'Artwork identifier';

COMMENT ON COLUMN artwork.artist_code IS
    'Artist identifier';

COMMENT ON COLUMN artwork.artwork_title IS
    'Artwork title';

COMMENT ON COLUMN artwork.artwork_date IS
    'Artwork date of work';

COMMENT ON COLUMN artwork.media_name IS
    'Media name';

COMMENT ON COLUMN artwork.min_price IS
    'Minimum pricing';

COMMENT ON COLUMN artwork.date_added_to_stock IS
    'Date added to stock';

COMMENT ON COLUMN artwork.artwork_style_no IS
    'Artwork_style_no';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artist_code,
                                                            artwork_no );

CREATE TABLE customer (
    cus_id          NUMBER(7) NOT NULL,
    cus_fname       VARCHAR2(50) NOT NULL,
    cus_lname       VARCHAR2(50) NOT NULL,
    business_name   VARCHAR2(50),
    cus_street      VARCHAR2(20) NOT NULL,
    cus_town        VARCHAR2(10) NOT NULL,
    cus_state       CHAR(3) NOT NULL,
    cus_tel_no      CHAR(10) NOT NULL
);

COMMENT ON COLUMN customer.cus_id IS
    'Customer identifier';

COMMENT ON COLUMN customer.cus_fname IS
    'Customerfirst  name';

COMMENT ON COLUMN customer.cus_lname IS
    'Customer last name';

COMMENT ON COLUMN customer.business_name IS
    'Customer business name';

COMMENT ON COLUMN customer.cus_street IS
    'Customer street';

COMMENT ON COLUMN customer.cus_town IS
    'Customer town';

COMMENT ON COLUMN customer.cus_state IS
    'Customer state';

COMMENT ON COLUMN customer.cus_tel_no IS
    'Customer phone number';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cus_id );

CREATE TABLE exhibit (
    exhibit_start   DATE NOT NULL,
    gal_id          NUMBER(2) NOT NULL,
    exhibit_end     DATE,
    feature         CHAR(1) DEFAULT 'Y' NOT NULL,
    artist_code     NUMBER(7) NOT NULL,
    artwork_no      NUMBER(2) NOT NULL,
    exhibit_no      NUMBER(4) NOT NULL
);

ALTER TABLE exhibit
    ADD CONSTRAINT chk_featured CHECK ( feature IN (
        'N',
        'Y'
    ) );

COMMENT ON COLUMN exhibit.exhibit_start IS
    'Exhibit start date';

COMMENT ON COLUMN exhibit.gal_id IS
    'Gallery identifier';

COMMENT ON COLUMN exhibit.exhibit_end IS
    'exhibit end date';

COMMENT ON COLUMN exhibit.feature IS
    'Featured in catalog';

COMMENT ON COLUMN exhibit.artist_code IS
    'Artist identifier';

COMMENT ON COLUMN exhibit.artwork_no IS
    'Artwork identifier';

COMMENT ON COLUMN exhibit.exhibit_no IS
    'Surrogate key exhibit identifier';

ALTER TABLE exhibit ADD CONSTRAINT exhibit_pk PRIMARY KEY ( exhibit_no );

ALTER TABLE exhibit ADD CONSTRAINT nk_exhibit UNIQUE ( exhibit_start,
                                                       gal_id );

CREATE TABLE gallery (
    gal_id          NUMBER(2) NOT NULL,
    gal_name        VARCHAR2(20) NOT NULL,
    manager_fname   VARCHAR2(20) NOT NULL,
    manager_lname   VARCHAR2(20) NOT NULL,
    gal_street      VARCHAR2(20) NOT NULL,
    gal_town        VARCHAR2(10) NOT NULL,
    gal_state       CHAR(3) NOT NULL,
    gal_tel_no      CHAR(10) NOT NULL,
    gal_open        VARCHAR2(4) NOT NULL,
    gal_close       VARCHAR2(4) NOT NULL
);

COMMENT ON COLUMN gallery.gal_id IS
    'Gallery identifier';

COMMENT ON COLUMN gallery.gal_name IS
    'Gallery name';

COMMENT ON COLUMN gallery.manager_fname IS
    'Managerfirst  name';

COMMENT ON COLUMN gallery.manager_lname IS
    'Manager last name';

COMMENT ON COLUMN gallery.gal_street IS
    'Gallery street';

COMMENT ON COLUMN gallery.gal_town IS
    'Gallery town';

COMMENT ON COLUMN gallery.gal_state IS
    'Gallery state';

COMMENT ON COLUMN gallery.gal_tel_no IS
    'Gallery phone number';

COMMENT ON COLUMN gallery.gal_open IS
    'Gallery open time';

COMMENT ON COLUMN gallery.gal_close IS
    'Gallery closing time';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gal_id );

CREATE TABLE sale (
    sale_id         NUMBER(7) NOT NULL,
    date_of_sale    DATE NOT NULL,
    sale_price      NUMBER(8, 2),
    cus_id          NUMBER(7) NOT NULL,
    artist_code     NUMBER(7) NOT NULL,
    artwork_no      NUMBER(2) NOT NULL,
    exhibit_start   DATE NOT NULL,
    gal_id          NUMBER(7) NOT NULL,
    exhibit_no      NUMBER(4) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'Sale identifier';

COMMENT ON COLUMN sale.date_of_sale IS
    'Date of sale';

COMMENT ON COLUMN sale.sale_price IS
    'Sale price';

COMMENT ON COLUMN sale.cus_id IS
    'Customer identifier';

COMMENT ON COLUMN sale.artist_code IS
    'Artist identifier';

COMMENT ON COLUMN sale.artwork_no IS
    'Artwork identifier';

COMMENT ON COLUMN sale.exhibit_start IS
    'Exhibit start date';

COMMENT ON COLUMN sale.gal_id IS
    'Gallery identifier';

COMMENT ON COLUMN sale.exhibit_no IS
    'Surrogate key exhibit identifier';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        artist_code
    ASC,
        artwork_no
    ASC );

CREATE UNIQUE INDEX sale__idxv1 ON
    sale (
        exhibit_start
    ASC,
        gal_id
    ASC );

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibit_no
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE status (
    artwork_status_date   DATE NOT NULL,
    artist_code           NUMBER(7) NOT NULL,
    artwork_no            NUMBER(2) NOT NULL,
    artwork_status        CHAR(1) DEFAULT 'S' NOT NULL,
    gal_id                NUMBER(2),
    status_id             NUMBER(7) NOT NULL
);

ALTER TABLE status
    ADD CONSTRAINT chk_status_type CHECK ( artwork_status IN (
        'D',
        'I',
        'R',
        'S',
        'T'
    ) );

COMMENT ON COLUMN status.artwork_status_date IS
    'artwork status date';

COMMENT ON COLUMN status.artist_code IS
    'Artist identifier';

COMMENT ON COLUMN status.artwork_no IS
    'Artwork identifier';

COMMENT ON COLUMN status.artwork_status IS
    'Artwork status';

COMMENT ON COLUMN status.gal_id IS
    'Gallery identifier';

COMMENT ON COLUMN status.status_id IS
    'Surrogate key of status';

ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( status_id );

ALTER TABLE status
    ADD CONSTRAINT nk_status UNIQUE ( artwork_status_date,
                                      artist_code,
                                      artwork_no );

CREATE TABLE style (
    artwork_style_no       NUMBER(3) NOT NULL,
    artwork_style          VARCHAR2(20) NOT NULL,
    artwork_parent_style   VARCHAR2(20)
);

COMMENT ON COLUMN style.artwork_style_no IS
    'Artwork_style_no';

COMMENT ON COLUMN style.artwork_style IS
    'Artwork style';

COMMENT ON COLUMN style.artwork_parent_style IS
    'Artwork_parent_style';

ALTER TABLE style ADD CONSTRAINT style_pk PRIMARY KEY ( artwork_style_no );

ALTER TABLE style ADD CONSTRAINT nk_style UNIQUE ( artwork_style );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE exhibit
    ADD CONSTRAINT artwork_display FOREIGN KEY ( artist_code,
                                                 artwork_no )
        REFERENCES artwork ( artist_code,
                             artwork_no );

ALTER TABLE sale
    ADD CONSTRAINT artwork_sold FOREIGN KEY ( artist_code,
                                              artwork_no )
        REFERENCES artwork ( artist_code,
                             artwork_no );

ALTER TABLE status
    ADD CONSTRAINT artwork_status FOREIGN KEY ( artist_code,
                                                artwork_no )
        REFERENCES artwork ( artist_code,
                             artwork_no );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_style FOREIGN KEY ( artwork_style_no )
        REFERENCES style ( artwork_style_no );

ALTER TABLE sale
    ADD CONSTRAINT exhibition_sale FOREIGN KEY ( exhibit_no )
        REFERENCES exhibit ( exhibit_no );

ALTER TABLE exhibit
    ADD CONSTRAINT gallery_display FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );

ALTER TABLE status
    ADD CONSTRAINT gallery_status FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );

ALTER TABLE sale
    ADD CONSTRAINT sales_to_customer FOREIGN KEY ( cus_id )
        REFERENCES customer ( cus_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             3
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

spool off;
set echo off;